language: java
addons:
    sonarcloud:
        organization: steinarb-github
        token: $SONAR_TOKEN
script:
    - travis_wait mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    - travis_wait mvn -B cobertura:cobertura coveralls:report

deploy:
    provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
